apiVersion: apps/v1
kind: Deployment
metadata:
  name: lab4-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lab4-app
  template:
    metadata:
      labels:
        app: lab4-app
    spec:
      containers:
        - name: lab4-app
          image: ghcr.io/roxanaluca/lab-java:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8899
          envFrom:
            - configMapRef:
                name: lab4-config
            - secretRef:
                name: lab4-secrets
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8899
            initialDelaySeconds: 15
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8899
            initialDelaySeconds: 30
            periodSeconds: 15
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
