apiVersion: v1
kind: ConfigMap
metadata:
  name: lab4-config
data:
  SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/appdb
  SPRING_DATASOURCE_USERNAME: appuser
  SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver
  SPRING_JPA_HIBERNATE_DDL_AUTO: update
  SPRING_FLYWAY_ENABLED: "false"
  SERVER_PORT: "8899"
