apiVersion: v1
kind: ConfigMap
metadata:
  name: lab4-config
data:
  SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432
  SPRING_DATASOURCE_USERNAME: appuser
  SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver
  SPRING_JPA_HIBERNATE_DDL_AUTO: update
  SPRING_FLYWAY_ENABLED: "false"
  SPRING_CLOUD_CONFIG_ENABLED: "false"
  SPRING_CLOUD_DISCOVERY_ENABLED: "false"
  SPRING_CLOUD_SERVICE_REGISTRY_AUTO_REGISTRATION_ENABLED: "false"
  EUREKA_CLIENT_ENABLED: "false"
  SPRING_KAFKA_LISTENER_AUTO_STARTUP: "false"
  SPRING_KAFKA_ADMIN_AUTO_CREATE: "false"
  SPRING_KAFKA_ADMIN_FAIL_FAST: "false"
  SPRING_KAFKA_BOOTSTRAP_SERVERS: localhost:0
  QUICKGRADE_CONNECT: "false"
  SERVER_PORT: "8899"
